# Generated by Django 4.1.2 on 2022-12-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='password',
            new_name='apelido_usuario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='username',
            new_name='cpf_cnpj_usuario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='nome_usuario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='celular_usuario',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cep_usuario',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='complemento_usuario',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco_usuario',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nome_completo_usuario',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='senha_usuario',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email_usuario',
            field=models.CharField(default='', max_length=30),
        ),
    ]
