# Generated by Django 4.1.2 on 2022-12-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_password_funcionario_apelido_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='token_usuario',
            field=models.CharField(default='', max_length=255),
        ),
    ]
