# Generated by Django 4.1.2 on 2022-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_funcionario_token_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_niveis',
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular_cliente',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep_cliente',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento_cliente',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj_cliente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_cliente',
            field=models.CharField(default='', max_length=255),
        ),
    ]
