# Generated by Django 4.1.2 on 2022-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_cliente_id_niveis_cliente_celular_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='senha_usuario',
            field=models.CharField(default='', max_length=255),
        ),
    ]
