# Generated by Django 4.1.2 on 2022-12-09 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiveisUsuario',
            fields=[
                ('id_niveis', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_niveis', models.CharField(max_length=20)),
                ('descricao_niveis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteFuncionario',
            fields=[
                ('id_usuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=30)),
                ('email_usuario', models.CharField(max_length=30)),
                ('apelido_usuario', models.CharField(max_length=20)),
                ('id_niveis', models.ForeignKey(max_length=3, on_delete=django.db.models.deletion.CASCADE, to='usuario.niveisusuario', validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
