# Generated by Django 4.1.2 on 2022-12-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientefuncionario',
            old_name='id_usuario',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='niveisusuario',
            old_name='id_niveis',
            new_name='id',
        ),
    ]
