# Generated by Django 4.1.2 on 2022-12-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_fabricacao_produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='data_validade_produto',
        ),
    ]
