# Generated by Django 4.1.2 on 2022-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_preco_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_produto',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='produtolucro',
            name='total_lucro',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
