# Generated by Django 4.1.2 on 2022-12-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_id_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='id_produto',
            new_name='id',
        ),
    ]
